version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    command: python3 -m bot
    depends_on:
      redis:
        condition: service_healthy
  nats:
    image: nats:2.10.17
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats-data/data:/data
      - ./nats-data/config/server.conf:/config/server.conf
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - redis-data:/data

volumes:
  redis-data: