version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    command: python3 -m bot
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - redis-data:/data

volumes:
  redis-data: